Repository Automattic/vaultpress, pull requests merged in 2019-12, with the labels that each got.

#75 Changing version numbers
  package.json
  readme.txt
  vaultpress.php
Labels: [Pri] Normal, [Status] Ready to Merge, [Type] Janitorial

#77 Change curly braces to square brackets
  vaultpress.php
Labels: [Status] Ready to Merge, [Type] Janitorial

#80 Bump autoloader to 1.3.6
  composer.json
  composer.lock
Labels: [Status] Ready to Merge, [Type] Janitorial

#79 Bump minimum to PHP 5.6
  readme.txt
  vaultpress.php
Labels: [Status] Ready to Merge, [Type] Bug
