Repository Automattic/vaultpress, pull requests merged in 2019-11, with the labels that each got.

#52 Admin Page: do not display a dashboard link if not registered.
  vaultpress.php
Labels: Admin Page, [Status] Needs Review, [Type] Bug

#49 Connect button: update link to current VaultPress page
  vaultpress.php
Labels: Admin Page, [Status] Needs Review, [Type] Enhancement

#34 Notices: only display notices in specific locations.
  vaultpress.php
Labels: Admin Page, [Pri] Normal, [Status] Needs Review, [Type] Enhancement

#54 Admin Page: update reset settings card wording.
  vaultpress.php
Labels: Admin Page, [Status] Needs Copy Review, [Status] Needs Review, [Type] Enhancement

#55 Notices: update wording for the VaultPress connection notice
  vaultpress.php
Labels: Notices, [Status] Needs Review, [Type] Enhancement

#71 Bump WP version
  readme.txt
Labels: [Type] Janitorial

#51 2.1 release: running changelog
  changelog.txt
  readme.txt
Labels: [Status] In Progress, [Type] Janitorial
