Repository Automattic/vaultpress, pull requests merged in 2019-06, with the labels that each got.

#6 Dashboard restyling
  images/automattic.svg
  images/noise.png
  images/plugin-shield-2x.png
  images/plugin-shield.png
  images/security.svg
  images/vaultpress.svg
  nav-styles.css
  styles.css
  vaultpress.php
Labels: Admin Page, [Status] Ready to Merge, [Type] Enhancement

#11 DNA: Use Jetpack autoloader
  composer.json
  composer.lock
  vaultpress.php
Labels: General, [Status] Ready to Merge

#14 Package.json: a base
  composer.json
  package.json
  yarn.lock
Labels: [Pri] Normal, [Status] Needs Review, [Type] Janitorial

#13 2.0 Beta Release
  changelog.txt
  readme.txt
  to-test.md
  vaultpress.php
Labels: [Pri] BLOCKER, [Status] Needs Review, [Type] Janitorial

#17 First pass at a Travis configuration file to lint files
  .gitignore
  .nvmrc
  .travis.yml
  composer.json
Labels: Unit Tests, [Status] Needs Review

#16 General: move VaultPress class to own file & add PHP53 shortcircuit
  class-vaultpress.php
  vaultpress.php
Labels: General, [Pri] BLOCKER, [Status] Ready to Merge

#18 Changelog: mention that the plugin now requires PHP 5.3
  readme.txt
Labels: [Pri] BLOCKER, [Status] Ready to Merge, [Type] Janitorial

#20 Fix Travis configuration
  .travis.yml
Labels: [Status] Ready to Merge, [Type] Bug, [Type] Janitorial

#19 Adds a new release script (branching only)
  .svnignore
  bin/release.php
Labels: [Status] Blocked / Hold, [Type] Janitorial

#27 Dashboard icon: bring back icon font used in wp-admin menu
  nav-styles.css
Labels: General, [Pri] BLOCKER, [Status] Needs Cherry-Pick, [Status] Ready to Merge, [Type] Bug

#32 Make spacing consistent in registration card
  class-vaultpress.php
Labels: Admin Page, [Status] Needs Cherry-Pick, [Status] Ready to Merge, [Type] Bug

#28 Plans link: open in a new window
  class-vaultpress.php
Labels: Admin Page, [Pri] Normal, [Status] Ready to Merge, [Type] Enhancement

#37 Autoloader: update to Jetpack Autoloader 1.1.0
  composer.json
  composer.lock
Labels: [Status] Needs Cherry-Pick, [Status] Ready to Merge, [Type] Janitorial

#30 Fix duplicated icon and bad layout for progress bars
  styles.css
Labels: Admin Page, [Status] Ready to Merge, [Type] Bug
