Repository Automattic/vaultpress, pull requests merged in 2019-07, with the labels that each got.

#39 Composer: do not delete composer.lock when cleaning
  package.json
Labels: [Status] Needs Review, [Type] Janitorial

#43 Changelog: update release date
  readme.txt
Labels: [Type] Janitorial

#45 Enqueue scripts in a better place
  class-vaultpress.php
Labels: [Status] Needs Cherry-Pick, [Status] Ready to Merge, [Type] Bug

#44 Notices: hook into a new vaultpress_notices hook in the VP dash.
  class-vaultpress.php
Labels: Admin Page, [Status] Needs Cherry-Pick, [Status] Needs Review, [Type] Bug

#57 General: revert to using a big entry file, with only the Logo moved to a different file
  class-jetpack-logo.php
  class-vaultpress.php
  vaultpress.php
Labels: Admin Page, [Status] Needs Review, [Type] Bug
