Repository Automattic/vaultpress, pull requests merged in 2020-08, with the labels that each got.

#100 Check for Jetpack version before loading Jetpack XML-RPC client
  vaultpress.php
Labels: [Status] Needs Review, [Type] Janitorial

#101 Version bump for 2.1.2
  package.json
  readme.txt
  vaultpress.php
Labels: [Status] Ready to Merge, [Type] Janitorial

#103 Miscellaneous 2.1.3 bookkeeping pulling back upstream.
  readme.txt
  vaultpress.php
Labels: [Status] Needs Review
